missing-static-assets: Add missing images needed by collectstatic
Without these files, collectstatic fails with:

```
python manage.py lms --settings=devstack collectstatic --noinput > /dev/null
Traceback (most recent call last):
  File "manage.py", line 95, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 169, in handle_noargs
    collected = self.collect()
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/management/commands/collectstatic.py", line 126, in collect
    for original_path, processed_path, processed in processor:
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 279, in post_process
    content = pattern.sub(converter, content)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 218, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 164, in url
    hashed_name = self.hashed_name(clean_name).replace('\\', '/')
  File "/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/staticfiles/storage.py", line 127, in hashed_name
    (clean_name, self))
ValueError: The file 'discussion/images/spinner.gif' could not be found with <pipeline.storage.PipelineCachedStorage object at 0x34f1210>.
```